"""Add messages and groups tables

Revision ID: 4179fe99122c
Revises: dbd7e46efe93
Create Date: 2025-05-26 01:07:46.241125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4179fe99122c'
down_revision = 'dbd7e46efe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groupes', 'date_creation',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('groupes_membres', 'date_ajout',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'pieces_jointes',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'pieces_jointes',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('groupes_membres', 'date_ajout',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('groupes', 'date_creation',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
