"""Add Message and Groupe models

Revision ID: a30d4e0bad8a
Revises: 4179fe99122c
Create Date: 2025-05-26 01:42:40.098747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a30d4e0bad8a'
down_revision = '4179fe99122c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('participants_conversation')
    # op.drop_table('conversations')
    op.add_column('groupes', sa.Column('createur_id', sa.Integer(), nullable=False))
    op.alter_column('groupes', 'date_creation',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('groupes_ibfk_1', 'groupes', type_='foreignkey')
    op.create_foreign_key(None, 'groupes', 'users', ['createur_id'], ['id'])
    op.drop_column('groupes', 'ecole_id')
    op.drop_column('groupes_membres', 'role')
    op.drop_column('groupes_membres', 'date_ajout')
    op.add_column('messages', sa.Column('lu', sa.Boolean(), nullable=True))
    op.alter_column('messages', 'sujet',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('messages', 'date_envoi',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('messages_ibfk_3', 'messages', type_='foreignkey')
    op.drop_constraint('messages_ibfk_5', 'messages', type_='foreignkey')
    op.drop_constraint('messages_ibfk_4', 'messages', type_='foreignkey')
    op.drop_column('messages', 'priorite')
    op.drop_column('messages', 'date_lecture')
    op.drop_column('messages', 'est_lu')
    op.drop_column('messages', 'statut')
    op.drop_column('messages', 'ecole_id')
    op.drop_column('messages', 'pieces_jointes')
    op.drop_column('messages', 'conversation_id')
    op.drop_column('messages', 'groupe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('groupe_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('conversation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('pieces_jointes', mysql.JSON(), nullable=True))
    op.add_column('messages', sa.Column('ecole_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('statut', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('messages', sa.Column('est_lu', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('date_lecture', mysql.DATETIME(), nullable=True))
    op.add_column('messages', sa.Column('priorite', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('messages_ibfk_4', 'messages', 'groupes', ['groupe_id'], ['id'])
    op.create_foreign_key('messages_ibfk_5', 'messages', 'conversations', ['conversation_id'], ['conversation_id'])
    op.create_foreign_key('messages_ibfk_3', 'messages', 'ecoles', ['ecole_id'], ['id'])
    op.alter_column('messages', 'date_envoi',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'sujet',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_column('messages', 'lu')
    op.add_column('groupes_membres', sa.Column('date_ajout', mysql.DATETIME(), nullable=False))
    op.add_column('groupes_membres', sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('groupes', sa.Column('ecole_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groupes', type_='foreignkey')
    op.create_foreign_key('groupes_ibfk_1', 'groupes', 'ecoles', ['ecole_id'], ['id'])
    op.alter_column('groupes', 'date_creation',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('groupes', 'createur_id')
    op.create_table('conversations',
    sa.Column('conversation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sujet', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_creation', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('dernier_message', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('participants_conversation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('utilisateur_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_utilisateur', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date_derniere_lecture', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], name='participants_conversation_ibfk_1'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], name='participants_conversation_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
