"""Add missing columns to Annonce model

Revision ID: dbd7e46efe93
Revises: 
Create Date: 2025-05-24 22:48:17.606659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd7e46efe93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonces', sa.Column('date_publication', sa.DateTime(), nullable=True))
    op.add_column('annonces', sa.Column('type_destinataire', sa.String(length=50), nullable=True))
    op.add_column('annonces', sa.Column('priorite', sa.String(length=20), nullable=True))
    op.add_column('annonces', sa.Column('ecole_id', sa.Integer(), nullable=True))
    op.add_column('annonces', sa.Column('auteur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'annonces', 'users', ['auteur_id'], ['id'])
    op.create_foreign_key(None, 'annonces', 'ecoles', ['ecole_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annonces', type_='foreignkey')
    op.drop_constraint(None, 'annonces', type_='foreignkey')
    op.drop_column('annonces', 'auteur_id')
    op.drop_column('annonces', 'ecole_id')
    op.drop_column('annonces', 'priorite')
    op.drop_column('annonces', 'type_destinataire')
    op.drop_column('annonces', 'date_publication')
    # ### end Alembic commands ###
